### ISSUE TITLE
Can't add, edit or drop table index

### ISSUE THREAD

**Issue by glushko311** [miracle2k/emma#3]
Environment: OS - Ubuntu 14.04
Emma 0.7

Steps to reproduce:

1.Insert a table
2.Choose bookmark "Indexes"
3.Try to add new index
4.Try to edit index 
5.Try to drop index

![default](https://cloud.githubusercontent.com/assets/10559084/6832875/cdbf885e-d331-11e4-99d3-8f86ef141f99.png)

**Comment by MrElectroNick** [comment]
Wrong repository! :-)
